- name: add kdenlive repo
  become: yes
  apt_repository:
    repo: 'ppa:kdenlive/kdenlive-stable'
    state: present

- name: install kdenlive
  become: yes
  apt:
    name: kdenlive
    state: present
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success

- name: install vlc
  become: yes
  apt:
    name: vlc
    state: present
