- name: add key
  become: yes
  apt_key:
    url: 'https://downloads.plex.tv/plex-keys/PlexSign.key'
    state: present

- name: add repo
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] https://downloads.plex.tv/repo/deb/ public main'
    state: present

- name: install plex
  become: yes
  apt:
    name: plexmediaserver
    state: present
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success