- name: add key
  become: yes
  apt_key:
    url: 'https://as-repository.openvpn.net/as-repo-public.gpg'
    state: present

- name: add repo
  become: yes
  apt_repository:
    repo: 'deb [arch=amd64] http://as-repository.openvpn.net/as/debian bionic main'
    state: present

- name: install openvpn-as
  become: yes
  apt:
    name: openvpn-as
    state: present
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success