- name: add docker group
  become: yes
  group:
    name: docker
    state: present
    gid: 666
    
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups }}"
    uid: "{{ item.uid }}"
    append: true
    create_home: true
    shell: /bin/bash
  with_items:
    - { name: docker, uid: 667, groups: "sudo,docker" }  
    - { name: plex, uid: 666, groups: "sudo,docker" }

- name: Set authorized key for remote user
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  with_items:
    - { name: docker, uid: 667, groups: "sudo,docker" }
    - { name: plex, uid: 666, groups: "sudo,docker" }
