- name: add google linux signing key
  become: yes
  apt_key:
    url: 'https://dl.google.com/linux/linux_signing_key.pub'
    state: present

- name: download package
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/google-chrome-stable_current_amd64.deb

- name: install chrome
  become: yes
  apt:
    deb: /tmp/google-chrome-stable_current_amd64.deb
