- name: add key
  become: yes
  apt_key:
    url: 'https://www.virtualbox.org/download/oracle_vbox_2016.asc'
    id: 'B9F8D658297AF3EFC18D5CDFA2F683C52980AECF'
    state: present

- name: add repo
  become: yes
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian cosmic contrib'
    state: present

- name: install virtualbox 5.2
  become: yes
  apt:
    name: virtualbox-5.2
    state: present
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success

