- stat:
    path: /usr/local/bin/terraform
  register: terraform

- name: download package
  get_url:
    url: https://releases.hashicorp.com/terraform/0.10.4/terraform_0.10.4_linux_amd64.zip
    dest: /tmp/terraform.zip
  when: terraform.stat.exists == False

- name: install terraform
  unarchive:
    src: /tmp/terraform.zip
    dest: /usr/local/bin/
    mode: 0755
  become: yes
  when: terraform.stat.exists == False
