- stat:
    path: /usr/bin/keybase
  register: keybase

- name: download package
  get_url:
    url: https://prerelease.keybase.io/keybase_amd64.deb
    dest: /tmp/keybase.deb
  when: keybase.stat.exists == False

- name: install keybase
  become: yes
  apt:
    deb: /tmp/keybase.deb
  when: keybase.stat.exists == False

- name: restart keybase
  command: run_keybase
  when: keybase.stat.exists == False

