- name: add key
  become: yes
  apt_key:
    url: 'https://cli-assets.heroku.com/apt/release.key'
    state: present

- name: add repo
  become: yes
  apt_repository:
    repo: 'deb https://cli-assets.heroku.com/branches/stable/apt ./'
    state: present

- name: install herokucli
  become: yes
  apt:
    name: heroku
    state: present
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success

