- name: add key
  become: yes
  apt_key:
    url: 'https://linux-packages.resilio.com/resilio-sync/key.asc'
    id: 'BE66CC4C3F171DE2'
    state: present

- name: add repo
  become: yes
  apt_repository:
    repo: 'deb http://linux-packages.resilio.com/resilio-sync/deb resilio-sync non-free'
    state: present

- name: install resilio sync
  become: yes
  apt:
    name: resilio-sync
    state: present
    update_cache: yes
  register: apt_res
  retries: 5
  until: apt_res is success

