version: '2'

services:
  proxy:
    extends:
      file: base.yml
      service: socket
    image: jwilder/nginx-proxy:latest
    container_name: proxy
    hostname: proxy
    ports:
      - 172.18.0.1:8088:80
    volumes:
      - /etc/ssl/certs:/etc/nginx/certs
      - /var/run/fcgiwrap.socket:/var/run/fcgiwrap.socket
      - /var/run/php-fpm.sock:/var/run/php-fpm.sock
      - ./config/proxy-ks5/etc/nginx:/etc/nginx
      - ./config/proxy-ks5/var/www:/var/www
      - /download:/download:ro
      - /content:/media:ro
      - /:/host
    environment:
      - VIRTUAL_HOST=proxy.pknw1.co.uk
      - VIRTUAL_PORT=80


  portainer:
    extends:
      file: base.yml
      service: base
    image: portainer/portainer-ce:latest
    profiles: ["frontend"]
    container_name: portainer
    hostname: portainer
    volumes:
      - ./config/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VIRTUAL_HOST=portainer.pknw1.co.uk
      - VIRTUAL_PORT=9000

  auth:
    extends:
      file: base.yml
      service: base
    image: pknw1/plexssov2:latest #pknw1/auth:latest #drkno/plexsso:latest
    container_name: auth
    hostname: auth
    volumes:
      - ./config/auth:/config
      - /:/host:ro
    environment:
      - VIRTUAL_HOST=sso.pknw1.co.uk
      - VIRTUAL_PORT=4200

  fakessh:
    container_name: fakessh
    image: fffaraz/fakessh:latest
    command: /log
    volumes:
      - ./config/fakessh:/config
      - ./config/fakessh/logs:/log
    ports:
      - 149.202.72.112:22:22

networks:
  proxy:
    external:
      name: proxy
